# ~/.config/fish/config.fish: DO NOT EDIT -- this file has been generated
# automatically by home-manager.

# Only execute this file once per shell.
set -q __fish_home_manager_config_sourced; and exit
set -g __fish_home_manager_config_sourced 1


# Source handler functions

fish_config theme choose "Catppuccin Macchiato"

status is-login; and begin

    # Login shell initialisation

end

status is-interactive; and begin

    # Abbreviations
    abbr --add -- ga 'git add'
    abbr --add -- gc 'git commit'
    abbr --add -- gco 'git checkout'
    abbr --add -- gcp 'git cherry-pick'
    abbr --add -- gdiff 'git diff'
    abbr --add -- gp 'git push'
    abbr --add -- gs 'git status'
    abbr --add -- gt 'git tag'

    # Aliases

    # Interactive shell initialisation
    fzf --fish | source

    set fish_greeting
    # Source local overrides (not managed by dotfiles)
    if test -f ~/.config/fish/config.local.fish
        source ~/.config/fish/config.local.fish
    end

    if test "$TERM" != dumb
        starship init fish | source

    end

    # add completions generated by Home Manager to $fish_complete_path
    begin
        set -l joined (string join " " $fish_complete_path)
        set -l prev_joined (string replace --regex "[^\s]*generated_completions.*" "" $joined)
        set -l post_joined (string replace $prev_joined "" $joined)
        set -l prev (string split " " (string trim $prev_joined))
        set -l post (string split " " (string trim $post_joined))
    end

end
