apiVersion: apps/v1
kind: Deployment
metadata:
  name: controller
  namespace: default
  labels:
    app: auxbot-controller
spec:
  replicas: 1
  selector:
    matchLabels:
      app: auxbot-controller
  template:
    metadata:
      labels:
        app: auxbot-controller
    spec:
      serviceAccountName: controller-service-account
      containers:
      - name: controller
        image: ghcr.io/dumspy/auxbot-controller:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 3000
        env:
        - name: K8S_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: WORKER_IMAGE
          value: "ghcr.io/dumspy/auxbot-worker:latest"
        resources:
          limits:
            cpu: 500m
            memory: 512Mi
          requests:
            cpu: 100m
            memory: 256Mi
---
apiVersion: v1
kind: Service
metadata:
  name: controller-service
  namespace: default
spec:
  selector:
    app: auxbot-controller
  ports:
  - port: 80
    targetPort: 3000
  type: ClusterIP