apiVersion: v1
kind: Service
metadata:
  name: auxbot-controller
  labels: 
    app: auxbot-controller
spec:
  selector:
    app: auxbot-controller
  ports:
  - name: api
    port: 80
    targetPort: 3000
  - name: grpc
    port: 50051
    targetPort: 50051
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: auxbot-controller
  labels:
    app: auxbot-controller
spec:
  replicas: 1
  selector:
    matchLabels:
      app: auxbot-controller
  template:
    metadata:
      labels:
        app: auxbot-controller
    spec:
      serviceAccountName: controller-service-account
      containers:
      - name: controller
        image: ghcr.io/dumspy/auxbot-controller:latest
        imagePullPolicy: Always 
        ports:
        - name: auxbot-controller-api
          containerPort: 3000
        - name: grpc
          containerPort: 50051
        livenessProbe:
          httpGet:
            path: /health
            port: 3000
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
        readinessProbe:
          httpGet:
            path: /health
            port: 3000
          initialDelaySeconds: 5
          periodSeconds: 5
        env:
        - name: K8S_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: WORKER_IMAGE
          value: "ghcr.io/dumspy/auxbot-worker:latest"
        - name: INACTIVITY_TIMEOUT_MINUTES
          value: "2"
        - name: DISCORD_CLIENT_ID
          valueFrom:
            secretKeyRef:
              name: auxbot-secrets
              key: DISCORD_CLIENT_ID
        - name: DISCORD_TOKEN
          valueFrom:
            secretKeyRef:
              name: auxbot-secrets
              key: DISCORD_TOKEN
        - name: SENTRY_DSN
          valueFrom:
            secretKeyRef:
              name: auxbot-secrets
              key: SENTRY_DSN
        resources:
          limits:
            cpu: 500m
            memory: 512Mi
          requests:
            cpu: 100m
            memory: 256Mi