{
  imports = [
    ./shell.nix
    ./zsh.nix
    ./fish.nix
    ./starship.nix
    ./fzf.nix
    ./direnv.nix
    ./git.nix
    ./ghostty.nix
    ./kubectl.nix
    ./lazyvim.nix
    ./tmux.nix
    ./tmux-sessionizer.nix
    ./wt.nix
    ./opencode.nix
    ./plannotator.nix
    ./agent-config.nix
    ./agent-browser.nix
    ./pi.nix
    ./dex.nix
    ./node-hardening.nix
    ./ssh.nix
    ./lazygit.nix
    ./ripgrep.nix
  ];
}
