{
  imports = [
    ./shell.nix
    ./zsh.nix
    ./fish.nix
    ./starship.nix
    ./fzf.nix
    ./direnv.nix
    ./git.nix
    ./ghostty.nix
    ./neovim.nix
    ./tmux.nix
    ./tmux-sessionizer.nix
    ./opencode.nix
    ./agent-skills.nix
    ./agent-browser.nix
    ./dex.nix
    ./ssh.nix
    ./lazygit.nix
  ];
}
