{
  imports = [
    ./shell.nix
    ./zsh.nix
    ./fish.nix
    ./starship.nix
    ./fzf.nix
    ./direnv.nix
    ./git.nix
    ./ghostty.nix
    ./lazyvim.nix
    ./tmux.nix
    ./tmux-sessionizer.nix
    ./tmux-worktree.nix
    ./git-clone-bare.nix
    ./opencode.nix
    ./agent-config.nix
    ./agent-browser.nix
    ./dex.nix
    ./ssh.nix
    ./lazygit.nix
  ];
}
