# pub keys
keys:
  - &darwin #TODO
  - &docker-host age1csvff7c37ne76l8mdqyy43845hw2r292lgdsa2d477pyypte9cvs6v4p4q
  - &wsl age1jn99r9xd7l023sc9uccmxsuzfzyu0cnmastyz8mqy8ry4sxevels84gr9z
creation_rules:
  - path_regex: /dev/stdin
    key_groups:
      - age:
        - *darwin
        - *docker-host
        - *wsl