# pub keys
keys:
  - &darwin age15epkhr4crqd0n9kwdk32hhezkexh5nevgpe4qqe0lhdnjtkp0qfqgcq3ha
  - &docker-host age1csvff7c37ne76l8mdqyy43845hw2r292lgdsa2d477pyypte9cvs6v4p4q
  - &wsl age1am3u47axkd29cddyuzsyhh43dy6uet4873nlqdu7dz309qnsf3rssf4qp6
creation_rules:
  - path_regex: /dev/stdin
    key_groups:
      - age:
        - *darwin
        - *docker-host
        - *wsl
