# pub keys
keys:
  - &darwin age15epkhr4crqd0n9kwdk32hhezkexh5nevgpe4qqe0lhdnjtkp0qfqgcq3ha
  - &docker-host age1csvff7c37ne76l8mdqyy43845hw2r292lgdsa2d477pyypte9cvs6v4p4q
  - &wsl age1uz89tr0xwm54sjfz9a7zncu7kh4a2u068m9zzqxkesck33xwecyspjhffl
creation_rules:
  - path_regex: /dev/stdin
    key_groups:
      - age:
        - *darwin
        - *docker-host
        - *wsl
